// const greekAndHebrewLetters = [
//   { name: "ω", latexFormat: "\\omega", value: [], type: "simple" },
//   { name: "α", latexFormat: "\\alpha", value: [], type: "simple" },
//   { name: "β", latexFormat: "\\beta", value: [], type: "simple" },
//   { name: "χ", latexFormat: "\\chi", value: [], type: "simple" },
//   { name: "δ", latexFormat: "\\delta", value: [], type: "simple" },
//   { name: "η", latexFormat: "\\eta", value: [], type: "simple" },
//   { name: "γ", latexFormat: "\\gamma", value: [], type: "simple" },
//   { name: "ι", latexFormat: "\\iota", value: [], type: "simple" },
//   { name: "κ", latexFormat: "\\kappa", value: [], type: "simple" },
//   { name: "λ", latexFormat: "\\lambda", value: [], type: "simple" },
//   { name: "µ", latexFormat: "\\mu", value: [], type: "simple" },
//   { name: "ν", latexFormat: "\\nu", value: [], type: "simple" },
//   { name: "o", latexFormat: "o", value: [], type: "simple" },
//   { name: "φ", latexFormat: "\\phi", value: [], type: "simple" },
//   { name: "π", latexFormat: "\\pi", value: [], type: "simple" },
//   { name: "ψ", latexFormat: "\\psi", value: [], type: "simple" },
//   { name: "ρ", latexFormat: "\\rho", value: [], type: "simple" },
//   { name: "σ", latexFormat: "\\sigma", value: [], type: "simple" },
//   { name: "τ", latexFormat: "\\tau", value: [], type: "simple" },
//   { name: "θ", latexFormat: "\\theta", value: [], type: "simple" },
//   { name: "υ", latexFormat: "\\upsilon", value: [], type: "simple" },
//   { name: "φ", latexFormat: "\\varphi", value: [], type: "simple" },
//   { name: "Ω", latexFormat: "\\Omega", value: [], type: "simple" },
//   { name: "ε", latexFormat: "\\epsilon", value: [], type: "simple" },
//   { name: "ϑ", latexFormat: "\\vartheta", value: [], type: "simple" },
//   { name: "ϴ", latexFormat: "\\vartheta", value: [], type: "simple" },
//   { name: "ϖ", latexFormat: "\\varpi", value: [], type: "simple" },
//   { name: "Φ", latexFormat: "\\Phi", value: [], type: "simple" },
//   { name: "ℵ", latexFormat: "\\aleph", value: [], type: "simple" },
//   { name: "ϱ", latexFormat: "\\varrho", value: [], type: "simple" },
//   { name: "Π", latexFormat: "\\Pi", value: [], type: "simple" },
//   { name: "i", latexFormat: "\\beth", value: [], type: "simple" },
//   { name: "ξ", latexFormat: "\\xi", value: [], type: "simple" },
//   { name: "ς", latexFormat: "\\varsigma", value: [], type: "simple" },
//   { name: "Ψ", latexFormat: "\\Psi", value: [], type: "simple" },
//   { name: "k", latexFormat: "\\daleth", value: [], type: "simple" },
//   { name: "ζ", latexFormat: "\\zeta", value: [], type: "simple" },
//   { name: "Σ", latexFormat: "\\Sigma", value: [], type: "simple" },
//   { name: "ג", latexFormat: "\\gimel", value: [], type: "simple" },
// ];

// const delimiters = [
//   { name: "⇑", latexFormat: "\\Uparrow", value: [], type: "simple" },
//   {
//     name: "⇓",
//     latexFormat: "\\Downarrow",
//     value: [],
//     type: "simple",
//   },
//   { name: "↑", latexFormat: "\\uparrow", value: [], type: "simple" },
//   {
//     name: "⌜",
//     latexFormat: "\\ulcorner",
//     value: [],
//     type: "simple",
//   },
//   { name: "⌞", latexFormat: "\\llcorner", value: [], type: "simple" },
//   {
//     name: "⌝",
//     latexFormat: "\\urcorner",
//     value: [],
//     type: "simple",
//   },
//   { name: "⌟", latexFormat: "\\lrcorner", value: [], type: "simple" },

//   { name: "⟨", latexFormat: "\\langle", value: [], type: "simple" },
//   { name: "⟩", latexFormat: "\\rangle", value: [], type: "simple" },

//   { name: "⌈", latexFormat: "\\lceil", value: [], type: "simple" },
//   { name: "⌉", latexFormat: "\\rceil", value: [], type: "simple" },
//   { name: "⌊", latexFormat: "\\lfloor", value: [], type: "simple" },
//   { name: "⌋", latexFormat: "\\rfloor", value: [], type: "simple" },
//   { name: "[", latexFormat: "[", value: [], type: "simple" },
//   { name: "]", latexFormat: "]", value: [], type: "simple" },
//   { name: "|", latexFormat: "|", value: [], type: "simple" },
//   { name: "∣", latexFormat: "\\vert", value: [], type: "simple" },
//   { name: "|", latexFormat: "\\|", value: [], type: "simple" },
//   { name: "∥", latexFormat: "\\Vert", value: [], type: "simple" },
//   { name: "{", latexFormat: "\\{", value: [], type: "simple" },
//   { name: "}", latexFormat: "\\}", value: [], type: "simple" },
//   { name: "\\", latexFormat: "\\\\", value: [], type: "simple" },
//   { name: "/", latexFormat: "/", value: [], type: "simple" },
//   { name: "b", latexFormat: "b", value: [], type: "simple" },
//   { name: "c", latexFormat: "c", value: [], type: "simple" },
//   { name: "d", latexFormat: "d", value: [], type: "simple" },
//   { name: "e", latexFormat: "e", value: [], type: "simple" },
//   { name: "h", latexFormat: "h", value: [], type: "simple" },
//   { name: "i", latexFormat: "i", value: [], type: "simple" },
//   { name: "k", latexFormat: "k", value: [], type: "simple" },
//   { name: "p", latexFormat: "p", value: [], type: "simple" },
//   { name: "q", latexFormat: "q", value: [], type: "simple" },
//   { name: "x", latexFormat: "x", value: [], type: "simple" },
//   { name: "y", latexFormat: "y", value: [], type: "simple" },
// ];

// const standardFunctionNames = [
//   { name: "arccos", latexFormat: "\\arccos", value: [], type: "simple" },
//   { name: "arcsin", latexFormat: "\\arcsin", value: [], type: "simple" },
//   { name: "arctan", latexFormat: "\\arctan", value: [], type: "simple" },
//   { name: "arg", latexFormat: "\\arg", value: [], type: "simple" },
//   { name: "cos", latexFormat: "\\cos", value: [], type: "simple" },
//   { name: "cosh", latexFormat: "\\cosh", value: [], type: "simple" },
//   { name: "cot", latexFormat: "\\cot", value: [], type: "simple" },
//   { name: "coth", latexFormat: "\\coth", value: [], type: "simple" },
//   { name: "csc", latexFormat: "\\csc", value: [], type: "simple" },
//   { name: "deg", latexFormat: "\\deg", value: [], type: "simple" },
//   { name: "det", latexFormat: "\\det", value: [], type: "simple" },
//   { name: "dim", latexFormat: "\\dim", value: [], type: "simple" },
//   { name: "exp", latexFormat: "\\exp", value: [], type: "simple" },
//   { name: "gcd", latexFormat: "\\gcd", value: [], type: "simple" },
//   { name: "hom", latexFormat: "\\hom", value: [], type: "simple" },
//   { name: "inf", latexFormat: "\\inf", value: [], type: "simple" },
//   { name: "∞", latexFormat: "\\infty", value: [], type: "simple" },

//   { name: "ker", latexFormat: "\\ker", value: [], type: "simple" },
//   { name: "lg", latexFormat: "\\lg", value: [], type: "simple" },
//   { name: "lim", latexFormat: "\\lim", value: [], type: "simple" },
//   { name: "liminf", latexFormat: "\\liminf", value: [], type: "simple" },
//   { name: "limsup", latexFormat: "\\limsup", value: [], type: "simple" },
//   { name: "ln", latexFormat: "\\ln", value: [], type: "simple" },
//   { name: "log", latexFormat: "\\log", value: [], type: "simple" },
//   { name: "max", latexFormat: "\\max", value: [], type: "simple" },
//   { name: "min", latexFormat: "\\min", value: [], type: "simple" },
//   { name: "Pr", latexFormat: "\\Pr", value: [], type: "simple" },
//   { name: "sec", latexFormat: "\\sec", value: [], type: "simple" },
//   { name: "sin", latexFormat: "\\sin", value: [], type: "simple" },
//   { name: "sinh", latexFormat: "\\sinh", value: [], type: "simple" },
//   { name: "sup", latexFormat: "\\sup", value: [], type: "simple" },
//   { name: "tan", latexFormat: "\\tan", value: [], type: "simple" },
//   { name: "tanh", latexFormat: "\\tanh", value: [], type: "simple" },
// ];

// const binaryOperationAndRelationSymbols = [
//   { name: "*", latexFormat: "\\ast", value: [], type: "simple" },
//   { name: "±", latexFormat: "\\pm", value: [], type: "simple" },
//   { name: "∩", latexFormat: "\\cap", value: [], type: "simple" },
//   { name: "⊲", latexFormat: "\\lhd", value: [], type: "simple" },
//   { name: "⋆", latexFormat: "\\star", value: [], type: "simple" },
//   { name: "∓", latexFormat: "\\mp", value: [], type: "simple" },
//   { name: "∪", latexFormat: "\\cup", value: [], type: "simple" },
//   { name: "⊳", latexFormat: "\\rhd", value: [], type: "simple" },
//   { name: "⋅", latexFormat: "\\cdot", value: [], type: "simple" },
//   { name: "⨿", latexFormat: "\\amalg", value: [], type: "simple" },
//   { name: "⊎", latexFormat: "\\uplus", value: [], type: "simple" },
//   { name: "◃", latexFormat: "\\triangleleft", value: [], type: "simple" },
//   { name: "∘", latexFormat: "\\circ", value: [], type: "simple" },
//   { name: "⊙", latexFormat: "\\odot", value: [], type: "simple" },
//   { name: "⊓", latexFormat: "\\sqcap", value: [], type: "simple" },
//   { name: "▹", latexFormat: "\\triangleright", value: [], type: "simple" },
//   { name: "∙", latexFormat: "\\bullet", value: [], type: "simple" },
//   { name: "⊕", latexFormat: "\\oplus", value: [], type: "simple" },
//   { name: "∧", latexFormat: "\\wedge", value: [], type: "simple" },
//   { name: "⊵", latexFormat: "\\unrhd", value: [], type: "simple" },
//   { name: "⋄", latexFormat: "\\diamond", value: [], type: "simple" },
//   { name: "⊘", latexFormat: "\\oslash", value: [], type: "simple" },
//   { name: "∨", latexFormat: "\\vee", value: [], type: "simple" },
//   { name: "▽", latexFormat: "\\bigtriangledown", value: [], type: "simple" },
//   { name: "×", latexFormat: "\\times", value: [], type: "simple" },
//   { name: "⊗", latexFormat: "\\otimes", value: [], type: "simple" },
//   { name: "†", latexFormat: "\\dagger", value: [], type: "simple" },
//   { name: "△", latexFormat: "\\bigtriangleup", value: [], type: "simple" },
//   { name: "÷", latexFormat: "\\div", value: [], type: "simple" },
//   { name: "≀", latexFormat: "\\wr", value: [], type: "simple" },
//   { name: "‡", latexFormat: "\\ddagger", value: [], type: "simple" },
//   { name: " \\", latexFormat: "\\setminus", value: [], type: "simple" },
//   { name: "⋅", latexFormat: "\\centerdot", value: [], type: "simple" },
//   { name: "⊼", latexFormat: "\\barwedge", value: [], type: "simple" },
//   { name: "⊻", latexFormat: "\\veebar", value: [], type: "simple" },
//   { name: "⊛", latexFormat: "\\circledast", value: [], type: "simple" },
//   { name: "⊞", latexFormat: "\\boxplus", value: [], type: "simple" },
//   { name: "⋏", latexFormat: "\\curlywedge", value: [], type: "simple" },
//   { name: "⋎", latexFormat: "\\curlyvee", value: [], type: "simple" },
//   { name: "⊚", latexFormat: "\\circledcirc", value: [], type: "simple" },
//   { name: "⊟", latexFormat: "\\boxminus", value: [], type: "simple" },
//   { name: "⋒", latexFormat: "\\Cap", value: [], type: "simple" },
//   { name: "⋓", latexFormat: "\\Cup", value: [], type: "simple" },
//   { name: "⊝", latexFormat: "\\circleddash", value: [], type: "simple" },
//   { name: "⊠", latexFormat: "\\boxtimes", value: [], type: "simple" },
//   { name: "⊥", latexFormat: "\\bot", value: [], type: "simple" },
//   { name: "⊤", latexFormat: "\\top", value: [], type: "simple" },
//   { name: "⋌", latexFormat: "\\rightthreetimes", value: [], type: "simple" },
//   { name: "≅", latexFormat: "\\divideontimes", value: [], type: "simple" },
//   { name: "⩞", latexFormat: "\\doublebarwedge", value: [], type: "simple" },
//   { name: "⋋", latexFormat: "\\leftthreetimes", value: [], type: "simple" },
//   { name: "≡", latexFormat: "\\equiv", value: [], type: "simple" },
//   { name: "≤", latexFormat: "\\leq", value: [], type: "simple" },
//   { name: "≥", latexFormat: "\\geq", value: [], type: "simple" },
//   { name: "⊥", latexFormat: "\\perp", value: [], type: "simple" },
//   { name: "≅", latexFormat: "\\cong", value: [], type: "simple" },
//   { name: "≺", latexFormat: "\\prec", value: [], type: "simple" },
//   { name: "≻", latexFormat: "\\succ", value: [], type: "simple" },
//   { name: "∣", latexFormat: "\\mid", value: [], type: "simple" },
//   { name: "≠", latexFormat: "\\neq", value: [], type: "simple" },
//   { name: "⪯", latexFormat: "\\preceq", value: [], type: "simple" },
//   { name: "⪯", latexFormat: "\\succeq", value: [], type: "simple" },
//   { name: "∥", latexFormat: "\\parallel", value: [], type: "simple" },
//   { name: "∼", latexFormat: "\\sim", value: [], type: "simple" },
//   { name: "≪", latexFormat: "\\ll", value: [], type: "simple" },
//   { name: "≫", latexFormat: "\\gg", value: [], type: "simple" },
//   { name: "⋈", latexFormat: "\\bowtie", value: [], type: "simple" },
//   { name: "≃", latexFormat: "\\simeq", value: [], type: "simple" },
//   { name: "⊂", latexFormat: "\\subset", value: [], type: "simple" },
//   { name: "⊃", latexFormat: "\\supset", value: [], type: "simple" },
//   { name: "⋈", latexFormat: "\\Join", value: [], type: "simple" },
//   { name: "≈", latexFormat: "\\approx", value: [], type: "simple" },
//   { name: "⊆", latexFormat: "\\subseteq", value: [], type: "simple" },
//   { name: "⊇", latexFormat: "\\supseteq", value: [], type: "simple" },
//   { name: "⋉", latexFormat: "\\ltimes", value: [], type: "simple" },
//   { name: "⋊", latexFormat: "\\rtimes", value: [], type: "simple" },
//   { name: "≐", latexFormat: "\\doteq", value: [], type: "simple" },
//   { name: "⊑", latexFormat: "\\sqsubseteq", value: [], type: "simple" },
//   { name: "⊒", latexFormat: "\\sqsupseteq", value: [], type: "simple" },
//   { name: "⌣", latexFormat: "\\smile", value: [], type: "simple" },
//   { name: "∝", latexFormat: "\\propto", value: [], type: "simple" },
//   { name: "⊣", latexFormat: "\\dashv", value: [], type: "simple" },
//   { name: "⊣", latexFormat: "\\vdash", value: [], type: "simple" },
//   { name: "⌢", latexFormat: "\\frown", value: [], type: "simple" },
//   { name: "⊨", latexFormat: "\\models", value: [], type: "simple" },
//   { name: "∈", latexFormat: "\\in", value: [], type: "simple" },
//   { name: "∋", latexFormat: "\\ni", value: [], type: "simple" },
//   { name: "∼", latexFormat: "\\sim", value: [], type: "simple" },
//   { name: "≦", latexFormat: "\\leqq", value: [], type: "simple" },
//   { name: "≧", latexFormat: "\\geqq", value: [], type: "simple" },
//   { name: "≶", latexFormat: "\\lessgtr", value: [], type: "simple" },
//   { name: "∼", latexFormat: "\\thicksim", value: [], type: "simple" },
//   { name: "⩽", latexFormat: "\\leqslant", value: [], type: "simple" },
//   { name: "⩾", latexFormat: "\\geqslant", value: [], type: "simple" },
//   { name: "⋚", latexFormat: "\\lesseqgtr", value: [], type: "simple" },
//   { name: "∽", latexFormat: "\\backsim", value: [], type: "simple" },
//   { name: "⪅", latexFormat: "\\lessapprox", value: [], type: "simple" },
//   { name: "⪆", latexFormat: "\\gtrapprox", value: [], type: "simple" },
//   { name: "⪋", latexFormat: "\\lesseqqgtr", value: [], type: "simple" },
//   { name: "⋍", latexFormat: "\\backsimeq", value: [], type: "simple" },
//   { name: "⋘", latexFormat: "\\lll", value: [], type: "simple" },
//   { name: "⋙", latexFormat: "\\ggg", value: [], type: "simple" },
//   { name: "⪌", latexFormat: "\\gtreqqless", value: [], type: "simple" },
//   { name: ",", latexFormat: "\\triangleq", value: [], type: "simple" },
//   { name: "l", latexFormat: "\\lessdot", value: [], type: "simple" },
//   { name: "m", latexFormat: "\\gtrdot", value: [], type: "simple" },
//   { name: "R", latexFormat: "\\gtreqless", value: [], type: "simple" },
//   { name: "$", latexFormat: "\\circeq", value: [], type: "simple" },
//   { name: ".", latexFormat: "\\lesssim", value: [], type: "simple" },
//   { name: "&", latexFormat: "\\gtrsim", value: [], type: "simple" },
//   { name: "≷", latexFormat: "\\gtrless", value: [], type: "simple" },
//   { name: "l", latexFormat: "\\bumpeq", value: [], type: "simple" },
//   { name: "0", latexFormat: "\\eqslantless", value: [], type: "simple" },
//   { name: "1", latexFormat: "\\eqslantgtr", value: [], type: "simple" },
//   { name: "", latexFormat: "\\backepsilon", value: [], type: "simple" },
//   { name: "m", latexFormat: "\\Bumpeq", value: [], type: "simple" },
//   { name: "-", latexFormat: "\\precsim", value: [], type: "simple" },
//   { name: "%", latexFormat: "\\succsim", value: [], type: "simple" },
//   { name: "G", latexFormat: "\\between", value: [], type: "simple" },
//   { name: "+", latexFormat: "\\doteqdot", value: [], type: "simple" },
//   { name: "w", latexFormat: "\\precapprox", value: [], type: "simple" },
//   { name: "v", latexFormat: "\\succapprox", value: [], type: "simple" },
//   { name: "t", latexFormat: "\\pitchfork", value: [], type: "simple" },
//   { name: "≈", latexFormat: "\\thickapprox", value: [], type: "simple" },
//   { name: "b", latexFormat: "\\Subset", value: [], type: "simple" },
//   { name: "c", latexFormat: "\\Supset", value: [], type: "simple" },
//   { name: "p", latexFormat: "\\shortmid", value: [], type: "simple" },
//   { name: ";", latexFormat: "\\fallingdotseq", value: [], type: "simple" },
//   { name: "j", latexFormat: "\\subseteqq", value: [], type: "simple" },
//   { name: "k", latexFormat: "\\supseteqq", value: [], type: "simple" },
//   { name: "a", latexFormat: "\\smallfrown", value: [], type: "simple" },
//   { name: ":", latexFormat: "\\risingdotseq", value: [], type: "simple" },
//   { name: "@", latexFormat: "\\sqsubset", value: [], type: "simple" },
//   { name: "A", latexFormat: "\\sqsupset", value: [], type: "simple" },
//   { name: "`", latexFormat: "\\smallsmile", value: [], type: "simple" },
//   { name: "∝", latexFormat: "\\varpropto", value: [], type: "simple" },
//   { name: "4", latexFormat: "\\preccurlyeq", value: [], type: "simple" },
//   { name: "<", latexFormat: "\\succcurlyeq", value: [], type: "simple" },
//   { name: " \\", latexFormat: "\\Vdash", value: [], type: "simple" },
//   { name: "∴", latexFormat: "\\therefore", value: [], type: "simple" },
//   { name: "2", latexFormat: "\\curlyeqprec", value: [], type: "simple" },
//   { name: "3", latexFormat: "\\curlyeqsucc", value: [], type: "simple" },
//   { name: "", latexFormat: "\\vDash", value: [], type: "simple" },
//   { name: "∵", latexFormat: "\\because", value: [], type: "simple" },
//   {
//     name: "J",
//     latexFormat: "\\blacktriangleleft",
//     value: [],
//     type: "simple",
//   },
//   {
//     name: "I",
//     latexFormat: "\\blacktriangleright",
//     value: [],
//     type: "simple",
//   },
//   { name: "", latexFormat: "\\Vvdash", value: [], type: "simple" },
//   { name: "P", latexFormat: "\\eqcirc", value: [], type: "simple" },
//   { name: "E", latexFormat: "\\trianglelefteq", value: [], type: "simple" },
//   { name: "D", latexFormat: "\\trianglerighteq", value: [], type: "simple" },
//   { name: "q", latexFormat: "\\shortparallel", value: [], type: "simple" },
//   { name: "6=", latexFormat: "\\neq", value: [], type: "simple" },
//   { name: "C", latexFormat: "\\vartriangleleft", value: [], type: "simple" },
//   { name: "B", latexFormat: "\\vartriangleright", value: [], type: "simple" },
//   { name: "/", latexFormat: "\\nshortparallel", value: [], type: "simple" },
//   { name: "", latexFormat: "\\ncong", value: [], type: "simple" },
//   { name: " \\", latexFormat: "\\nleq", value: [], type: "simple" },
//   { name: "*", latexFormat: "\\nsubseteq", value: [], type: "simple" },
//   { name: "-", latexFormat: "\\nmid", value: [], type: "simple" },
//   { name: "", latexFormat: "\\nleqq", value: [], type: "simple" },
//   { name: "", latexFormat: "\\ngeqq", value: [], type: "simple" },
//   { name: "+", latexFormat: "\\nsupseteq", value: [], type: "simple" },
//   { name: "∦", latexFormat: "\\nparallel", value: [], type: "simple" },
//   { name: " \\", latexFormat: "\\nleqslant", value: [], type: "simple" },
//   { name: " \\", latexFormat: "\\ngeqslant", value: [], type: "simple" },
//   { name: " \\", latexFormat: "\\nsubseteqq", value: [], type: "simple" },
//   { name: ".", latexFormat: "\\nshortmid", value: [], type: "simple" },
//   { name: "≮", latexFormat: "\\nless", value: [], type: "simple" },
//   { name: "≯", latexFormat: "\\ngtr", value: [], type: "simple" },
//   { name: "#", latexFormat: "\\nsupseteqq", value: [], type: "simple" },
//   { name: "/", latexFormat: "\\nshortparallel", value: [], type: "simple" },
//   { name: "⊀", latexFormat: "\\nprec", value: [], type: "simple" },
//   { name: " \\", latexFormat: "\\nsucc", value: [], type: "simple" },
//   { name: "(", latexFormat: "\\subsetneq", value: [], type: "simple" },
//   { name: "", latexFormat: "\\nsim", value: [], type: "simple" },
//   { name: "", latexFormat: "\\npreceq", value: [], type: "simple" },
//   { name: "", latexFormat: "\\nsucceq", value: [], type: "simple" },
//   { name: ")", latexFormat: "\\supsetneq", value: [], type: "simple" },
//   { name: "3", latexFormat: "\\nVDash", value: [], type: "simple" },
//   { name: "", latexFormat: "\\precnapprox", value: [], type: "simple" },
//   { name: "", latexFormat: "\\succnapprox", value: [], type: "simple" },
//   { name: "$", latexFormat: "\\subsetneqq", value: [], type: "simple" },
//   { name: "2", latexFormat: "\\nvDash", value: [], type: "simple" },
//   { name: "", latexFormat: "\\precnsim", value: [], type: "simple" },
//   { name: "", latexFormat: "\\succnsim", value: [], type: "simple" },
//   { name: "%", latexFormat: "\\supsetneqq", value: [], type: "simple" },
//   { name: "0", latexFormat: "\\nvdash", value: [], type: "simple" },
//   { name: "", latexFormat: "\\lnapprox", value: [], type: "simple" },
//   { name: "", latexFormat: "\\gnapprox", value: [], type: "simple" },
//   { name: " \\", latexFormat: "\\varsubsetneq", value: [], type: "simple" },
//   { name: "6", latexFormat: "\\ntriangleleft", value: [], type: "simple" },
//   { name: "", latexFormat: "\\lneq", value: [], type: "simple" },
//   { name: " \\", latexFormat: "\\gneq", value: [], type: "simple" },
//   { name: "!", latexFormat: "\\varsupsetneq", value: [], type: "simple" },
//   { name: "5", latexFormat: "\\ntrianglelefteq", value: [], type: "simple" },
//   { name: "", latexFormat: "\\lneqq", value: [], type: "simple" },
//   { name: "	", latexFormat: "\\gneqq", value: [], type: "simple" },
//   { name: "&", latexFormat: "\\varsubsetneqq", value: [], type: "simple" },
//   { name: "7", latexFormat: "\\ntriangleright", value: [], type: "simple" },
//   { name: "", latexFormat: "\\lnsim", value: [], type: "simple" },
//   { name: "", latexFormat: "\\gnsim", value: [], type: "simple" },
//   { name: "'", latexFormat: "\\varsupsetneqq", value: [], type: "simple" },
//     // { name: "≜", latexFormat: "\\triangleq", value: [], type: "simple" },
// { name: "⋖", latexFormat: "\\lessdot", value: [], type: "simple" },
// { name: "⋗", latexFormat: "\\gtrdot", value: [], type: "simple" },
// { name: "⋛", latexFormat: "\\gtreqless", value: [], type: "simple" },
// { name: "≗", latexFormat: "\\circeq", value: [], type: "simple" },
// { name: "≲", latexFormat: "\\lesssim", value: [], type: "simple" },
// { name: "≳", latexFormat: "\\gtrsim", value: [], type: "simple" },
// { name: "≷", latexFormat: "\\gtrless", value: [], type: "simple" },
// { name: "≏", latexFormat: "\\bumpeq", value: [], type: "simple" },
// { name: "⪕", latexFormat: "\\eqslantless", value: [], type: "simple" },
// { name: "⪖", latexFormat: "\\eqslantgtr", value: [], type: "simple" },
// { name: "∍", latexFormat: "\\backepsilon", value: [], type: "simple" },
// { name: "≎", latexFormat: "\\Bumpeq", value: [], type: "simple" },
// { name: "≾", latexFormat: "\\precsim", value: [], type: "simple" },
// { name: "≿", latexFormat: "\\succsim", value: [], type: "simple" },
// { name: "≬", latexFormat: "\\between", value: [], type: "simple" },
// { name: "≑", latexFormat: "\\doteqdot", value: [], type: "simple" },
// { name: "⪷", latexFormat: "\\precapprox", value: [], type: "simple" },
// { name: "⪸", latexFormat: "\\succapprox", value: [], type: "simple" },
// { name: "⋔", latexFormat: "\\pitchfork", value: [], type: "simple" },
// { name: "≈", latexFormat: "\\thickapprox", value: [], type: "simple" },
// { name: "⋐", latexFormat: "\\Subset", value: [], type: "simple" },
// { name: "⋑", latexFormat: "\\Supset", value: [], type: "simple" },
// { name: "∣", latexFormat: "\\shortmid", value: [], type: "simple" },
// { name: "≒", latexFormat: "\\fallingdotseq", value: [], type: "simple" },
// { name: "⫅", latexFormat: "\\subseteqq", value: [], type: "simple" },
// { name: "⫆", latexFormat: "\\supseteqq", value: [], type: "simple" },
// { name: "⌢", latexFormat: "\\smallfrown", value: [], type: "simple" },
// { name: "≓", latexFormat: "\\risingdotseq", value: [], type: "simple" },
// { name: "⊏", latexFormat: "\\sqsubset", value: [], type: "simple" },
// { name: "⊐", latexFormat: "\\sqsupset", value: [], type: "simple" },
// { name: "⌣", latexFormat: "\\smallsmile", value: [], type: "simple" },
// { name: "∝", latexFormat: "\\varpropto", value: [], type: "simple" },
// { name: "≼", latexFormat: "\\preccurlyeq", value: [], type: "simple" },
// { name: "≼", latexFormat: "\\succcurlyeq", value: [], type: "simple" },
// { name: "⊩", latexFormat: "\\Vdash", value: [], type: "simple" },
// { name: "∴", latexFormat: "\\therefore", value: [], type: "simple" },
// { name: "⋞", latexFormat: "\\curlyeqprec", value: [], type: "simple" },
// { name: "⋟", latexFormat: "\\curlyeqsucc", value: [], type: "simple" },
// { name: "⊨", latexFormat: "\\vDash", value: [], type: "simple" },
// { name: "∵", latexFormat: "\\because", value: [], type: "simple" },
// {
//   name: "◀",
//   latexFormat: "\\blacktriangleleft",
//   value: [],
//   type: "simple",
// },
// {
//   name: "▶",
//   latexFormat: "\\blacktriangleright",
//   value: [],
//   type: "simple",
// },
// { name: "⊪", latexFormat: "\\Vvdash", value: [], type: "simple" },
// { name: "≖", latexFormat: "\\eqcirc", value: [], type: "simple" },
// { name: "⊴", latexFormat: "\\trianglelefteq", value: [], type: "simple" },
// { name: "⊵", latexFormat: "\\trianglerighteq", value: [], type: "simple" },
// { name: "∥", latexFormat: "\\shortparallel", value: [], type: "simple" },
// { name: "≠", latexFormat: "\\neq", value: [], type: "simple" },
// { name: "⊲", latexFormat: "\\vartriangleleft", value: [], type: "simple" },
// { name: "⊳", latexFormat: "\\vartriangleright", value: [], type: "simple" },
// { name: "∦", latexFormat: "\\nshortparallel", value: [], type: "simple" },
// { name: "≆", latexFormat: "\\ncong", value: [], type: "simple" },
// { name: "≰", latexFormat: "\\nleq", value: [], type: "simple" },
// { name: "⊈", latexFormat: "\\nsubseteq", value: [], type: "simple" },
// { name: "∤", latexFormat: "\\nmid", value: [], type: "simple" },
// { name: "≰", latexFormat: "\\nleqq", value: [], type: "simple" },
// { name: "≱", latexFormat: "\\ngeqq", value: [], type: "simple" },
// { name: "⊉", latexFormat: "\\nsupseteq", value: [], type: "simple" },
// { name: "∦", latexFormat: "\\nparallel", value: [], type: "simple" },
// { name: "≰", latexFormat: "\\nleqslant", value: [], type: "simple" },
// { name: "≱", latexFormat: "\\ngeqslant", value: [], type: "simple" },
// { name: "⊈", latexFormat: "\\nsubseteqq", value: [], type: "simple" },
// { name: "∤", latexFormat: "\\nshortmid", value: [], type: "simple" },
// { name: "≮", latexFormat: "\\nless", value: [], type: "simple" },
// { name: "≯", latexFormat: "\\ngtr", value: [], type: "simple" },
// { name: "⊉", latexFormat: "\\nsupseteqq", value: [], type: "simple" },
// { name: "∦", latexFormat: "\\nshortparallel", value: [], type: "simple" },
// { name: "⊀", latexFormat: "\\nprec", value: [], type: "simple" },
// { name: "⊁", latexFormat: "\\nsucc", value: [], type: "simple" },
// { name: "⊊", latexFormat: "\\subsetneq", value: [], type: "simple" },
// { name: "≁", latexFormat: "\\nsim", value: [], type: "simple" },
// { name: "⋠", latexFormat: "\\npreceq", value: [], type: "simple" },
// { name: "⋡", latexFormat: "\\nsucceq", value: [], type: "simple" },
// { name: "⊋", latexFormat: "\\supsetneq", value: [], type: "simple" },
// { name: "⊯", latexFormat: "\\nVDash", value: [], type: "simple" },
// { name: "⪹", latexFormat: "\\precnapprox", value: [], type: "simple" },
// { name: "⪺", latexFormat: "\\succnapprox", value: [], type: "simple" },
// { name: "⫋", latexFormat: "\\subsetneqq", value: [], type: "simple" },
// { name: "⊭", latexFormat: "\\nvDash", value: [], type: "simple" },
// { name: "⋨", latexFormat: "\\precnsim", value: [], type: "simple" },
// { name: "⋩", latexFormat: "\\succnsim", value: [], type: "simple" },
// { name: "⫌", latexFormat: "\\supsetneqq", value: [], type: "simple" },
// { name: "⊬", latexFormat: "\\nvdash", value: [], type: "simple" },
// { name: "⪉", latexFormat: "\\lnapprox", value: [], type: "simple" },
// { name: "⪊", latexFormat: "\\gnapprox", value: [], type: "simple" },
// { name: "⊊", latexFormat: "\\varsubsetneq", value: [], type: "simple" },
// { name: "⋪", latexFormat: "\\ntriangleleft", value: [], type: "simple" },
// { name: "⪇", latexFormat: "\\lneq", value: [], type: "simple" },
// { name: "⪈", latexFormat: "\\gneq", value: [], type: "simple" },
// { name: "⪈", latexFormat: "\\varsupsetneq", value: [], type: "simple" },
// { name: "⋬", latexFormat: "\\ntrianglelefteq", value: [], type: "simple" },
// { name: "≨", latexFormat: "\\lneqq", value: [], type: "simple" },
// { name: "≩", latexFormat: "\\gneqq", value: [], type: "simple" },
// { name: "⫋", latexFormat: "\\varsubsetneqq", value: [], type: "simple" },
// { name: "⋫", latexFormat: "\\ntriangleright", value: [], type: "simple" },
// { name: "⋦", latexFormat: "\\lnsim", value: [], type: "simple" },
// { name: "⋧", latexFormat: "\\gnsim", value: [], type: "simple" },
// { name: "⫌", latexFormat: "\\varsupsetneqq", value: [], type: "simple" },
// ];

// const arrowSymbols = [
//   { name: "←", latexFormat: "\\leftarrow", value: [], type: "simple" },
//   { name: "⟵", latexFormat: "\\longleftarrow", value: [], type: "simple" },
//   { name: "↑", latexFormat: "\\uparrow", value: [], type: "simple" },
//   { name: "⇐", latexFormat: "\\Leftarrow", value: [], type: "simple" },
//   { name: "⟸", latexFormat: "\\Longleftarrow", value: [], type: "simple" },
//   { name: "⇑", latexFormat: "\\Uparrow", value: [], type: "simple" },
//   { name: "→", latexFormat: "\\rightarrow", value: [], type: "simple" },
//   { name: "⟶", latexFormat: "\\longrightarrow", value: [], type: "simple" },
//   { name: "↓", latexFormat: "\\downarrow", value: [], type: "simple" },
//   { name: "⇒", latexFormat: "\\Rightarrow", value: [], type: "simple" },
//   { name: "⟹", latexFormat: "\\Longrightarrow", value: [], type: "simple" },
//   { name: "⇓", latexFormat: "\\Downarrow", value: [], type: "simple" },
//   { name: "↔", latexFormat: "\\leftrightarrow", value: [], type: "simple" },
//   {
//     name: "⟷",
//     latexFormat: "\\longleftrightarrow",
//     value: [],
//     type: "simple",
//   },
//   { name: "↕", latexFormat: "\\updownarrow", value: [], type: "simple" },
//   { name: "⇔", latexFormat: "\\Leftrightarrow", value: [], type: "simple" },
//   {
//     name: "⟺",
//     latexFormat: "\\Longleftrightarrow",
//     value: [],
//     type: "simple",
//   },
//   { name: "⇕", latexFormat: "\\Updownarrow", value: [], type: "simple" },
//   { name: "↦", latexFormat: "\\mapsto", value: [], type: "simple" },
//   { name: "⟼", latexFormat: "\\longmapsto", value: [], type: "simple" },
//   { name: "↗", latexFormat: "\\nearrow", value: [], type: "simple" },
//   { name: "↩", latexFormat: "\\hookleftarrow", value: [], type: "simple" },
//   { name: "↪", latexFormat: "\\hookrightarrow", value: [], type: "simple" },
//   { name: "↘", latexFormat: "\\searrow", value: [], type: "simple" },
//   { name: "↼", latexFormat: "\\leftharpoonup", value: [], type: "simple" },
//   { name: "⇀", latexFormat: "\\rightharpoonup", value: [], type: "simple" },
//   { name: "↙", latexFormat: "\\swarrow", value: [], type: "simple" },
//   { name: "↽", latexFormat: "\\leftharpoondown", value: [], type: "simple" },
//   { name: "⇁", latexFormat: "\\rightharpoondown", value: [], type: "simple" },
//   { name: "↖", latexFormat: "\\nwarrow", value: [], type: "simple" },
//   {
//     name: "⇌",
//     latexFormat: "\\rightleftharpoons",
//     value: [],
//     type: "simple",
//   },
//   { name: "⇝", latexFormat: "\\leadsto", value: [], type: "simple" },
//   { name: "⇢", latexFormat: "\\dashrightarrow", value: [], type: "simple" },
//   { name: "⇠", latexFormat: "\\dashleftarrow", value: [], type: "simple" },
//   { name: "⇆", latexFormat: "\\leftrightarrows", value: [], type: "simple" },
//   { name: "⇚", latexFormat: "\\Lleftarrow", value: [], type: "simple" },
//   { name: "↞", latexFormat: "\\twoheadleftarrow", value: [], type: "simple" },
//   { name: "↢", latexFormat: "\\leftarrowtail", value: [], type: "simple" },
//   { name: "↫", latexFormat: "\\looparrowleft", value: [], type: "simple" },
//   {
//     name: "⇋",
//     latexFormat: "\\leftrightharpoons",
//     value: [],
//     type: "simple",
//   },
//   { name: "↶", latexFormat: "\\curvearrowleft", value: [], type: "simple" },
//   {
//     name: "↺",
//     latexFormat: "\\circlearrowleft",
//     value: [],
//     type: "simple",
//   },
//   { name: "↰", latexFormat: "\\Lsh", value: [], type: "simple" },
//   { name: "⇈", latexFormat: "\\upuparrows", value: [], type: "simple" },
//   { name: "↿", latexFormat: "\\upharpoonleft", value: [], type: "simple" },
//   { name: "⇃", latexFormat: "\\downharpoonleft", value: [], type: "simple" },
//   { name: "⊸", latexFormat: "\\multimap", value: [], type: "simple" },
//   {
//     name: "↭",
//     latexFormat: "\\leftrightsquigarrow",
//     value: [],
//     type: "simple",
//   },
//   { name: "⇉", latexFormat: "\\rightrightarrows", value: [], type: "simple" },
//   { name: "⇄", latexFormat: "\\rightleftarrows", value: [], type: "simple" },
//   { name: "⇉", latexFormat: "\\rightrightarrows", value: [], type: "simple" },
//   { name: "⇄", latexFormat: "\\rightleftarrows", value: [], type: "simple" },
//   {
//     name: "↠",
//     latexFormat: "\\twoheadrightarrow",
//     value: [],
//     type: "simple",
//   },
//   { name: "↣", latexFormat: "\\rightarrowtail", value: [], type: "simple" },
//   { name: "↬", latexFormat: "\\looparrowright", value: [], type: "simple" },
//   {
//     name: "⇌",
//     latexFormat: "\\rightleftharpoons",
//     value: [],
//     type: "simple",
//   },
//   { name: "↷", latexFormat: "\\curvearrowright", value: [], type: "simple" },
//   { name: "↻", latexFormat: "\\circlearrowright", value: [], type: "simple" },
//   { name: "↱", latexFormat: "\\Rsh", value: [], type: "simple" },
//   { name: "⇊", latexFormat: "\\downdownarrows", value: [], type: "simple" },
//   { name: "↾", latexFormat: "\\upharpoonright", value: [], type: "simple" },
//   { name: "⇂", latexFormat: "\\downharpoonright", value: [], type: "simple" },
//   {
//     name: "⇝",
//     latexFormat: "\\rightsquigarrow",
//     value: [],
//     type: "simple",
//   },
//   { name: "↚", latexFormat: "\\nleftarrow", value: [], type: "simple" },
//   { name: "↛", latexFormat: "\\nrightarrow", value: [], type: "simple" },
//   { name: "⇍", latexFormat: "\\nLeftarrow", value: [], type: "simple" },
//   { name: "⇏", latexFormat: "\\nRightarrow", value: [], type: "simple" },
//   { name: "↮", latexFormat: "\\nleftrightarrow", value: [], type: "simple" },
//   { name: "⇎", latexFormat: "\\nLeftrightarrow", value: [], type: "simple" },
// ];
